name: Testing
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          /usr/bin/bash "${GITHUB_WORKSPACE}/buildConfigs.sh"
        env:
          firebaseAppCheckKey: '${{ secrets.FIREBASE_APP_CHECK_KEY }}'
          projectId: '${{ secrets.FIREBASE_PROJECTID }}'
      - name: "debug build"
        run: yarn && yarn run build:debug
      - uses: browser-actions/setup-chrome@latest
      - run: |
          export CHROMIUM_BIN=$(which chrome)
          CHROMIUM_VERSION=$(chrome --version)
          echo "Using CHROMIUM_BIN=${CHROMIUM_BIN} version=${CHROMIUM_VERSION}"
      - name: "test"
        run: yarn run test:ci
