name: Testing
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          /usr/bin/bash "${GITHUB_WORKSPACE}/buildConfigs.sh"
        env:
          firebaseAppCheckKey: '${{ secrets.FIREBASE_APP_CHECK_KEY }}'
          projectId: '${{ secrets.FIREBASE_PROJECTID }}'
      - name: "production build"
        if: ${{ github.repository == 'BrightChain/quri' }}
        run: yarn && yarn run lint && yarn run build
      - name: "debug build"
        if: ${{ github.repository == 'BrightChain/quri-dev' }}
        run: yarn && yarn run build:debug
      - name: "fail build"
        if: ${{ github.repository != 'BrightChain/quri' && github.repository != 'BrightChain/quri-dev' }}
        run: "exit 1"
      - name: "test"
        run: yarn run test
